### PR TITLE
Add files to generate documentation locally

### PR DESCRIPTION
**Pull request by b-reyes**
Currently there does not exist a simple way to generate the documentation locally. In this PR I have completed the following items, which make it simpler to generate the documentation locally:
- Added the yaml file `conda_dev_env.yml`, which allows someone to easily create a conda environment with all necessary python libraries used to generate the documentation.
- Modified `conf.py` so that it specifies the html theme to use
- Added `Makefile` that allows individuals to easily generate, view, and clean up the documentation locally
- Added the section `Generating Documentation Locally` to `README.md`, which describes how to create a conda environment and generate the documentation locally. 

@LRFreeborn and @Trevhall52 are we OK with my addition of the `Generating Documentation Locally` section to the readme? Also, please let me know if you have any suggested changes for the added readme section.

### CODE REVIEW

**Review by LRFreeborn — APPROVED** [review]
Everything looks good to me. I was able to create a conda environment using the provided yaml, run `make html` and then `make view`. The instructions are clear and to the point.

**Comment by Trevhall52** [comment]
This looks good to me. One thing to note is that windows users do not, by default, have access to any Linux subsystem for use of commands such as make. Nonetheless, once Windows users have access to this (or similar) the instructions are clear and successful.

**Comment by b-reyes** [comment]
> This looks good to me. One thing to note is that windows users do not, by default, have access to any Linux subsystem for use of commands such as make. Nonetheless, once Windows users have access to this (or similar) the instructions are clear and successful.

@Trevhall52 thank you very much for the comment. I will add a comment in the readme for Window's users.

**Comment by b-reyes** [comment]
I have added a comment to the readme for Windows users. I will go ahead and merge this into main.

**Pull request merged**
